### ISSUE TITLE
javax.net.ssl.SSLException: SSLEngine closed already

### ISSUE THREAD

**Issue by 97hknl** [cloudbees-oss/zendesk-java-client#277]
I am trying to iterate over ll tickets by doing `for(Ticket ticket : zd.getTickets())`. If I keep running it for all tickets, I get this error:

javax.net.ssl.SSLException: SSLEngine closed already
Exception in thread "main" java.io.IOException: Stream closed
	at sun.nio.cs.StreamEncoder.ensureOpen(StreamEncoder.java:45)
	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:140)
	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
	at Main.close(Main.java:55)
	at Main.start(Main.java:50)
	at Main.main(Main.java:28)

Does anyone know how to solve it?

**Comment by duemir** [comment]
Hi @97hknl ,

Is that a full stack trace? There's no reference to this library in it and the `javax.net.ssl.SSLException: SSLEngine closed already` seems to be disconnected from the rest of the stack trace. Can you please give more information if you are still affected.
