### ISSUE TITLE
Java Heap Space issue when trying to log large responses

### ISSUE THREAD

**Issue by barryskal** [cloudbees-oss/zendesk-java-client#294]
**Describe the bug**
I'm getting exception thrown because my container is out of heap space when trying to log a response. Here is the stack trace:

```
org.zendesk.client.v2.ZendeskException: java.lang.OutOfMemoryError: Java heap space
	at org.zendesk.client.v2.Zendesk.complete(Zendesk.java:2250)
	at org.zendesk.client.v2.Zendesk.access$1400(Zendesk.java:95)
	at org.zendesk.client.v2.Zendesk$PagedIterable$PagedIterator.hasNext(Zendesk.java:2482)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOfRange(Arrays.java:3664)
	at java.lang.StringBuffer.toString(StringBuffer.java:669)
	at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:240)
	at au.com.helixta.util.log.AbstractLogger.log(AbstractLogger.java:68)
	at au.com.helixta.util.log.AbstractLogger.debug(AbstractLogger.java:163)
	at au.com.helixta.util.log.MultiLoggerBase.debug(MultiLoggerFactory.java:318)
	at org.zendesk.client.v2.Zendesk.logResponse(Zendesk.java:2201)
	at org.zendesk.client.v2.Zendesk.access$200(Zendesk.java:95)
	at org.zendesk.client.v2.Zendesk$PagedAsyncListCompletionHandler.onCompleted(Zendesk.java:2050)
	at org.zendesk.client.v2.Zendesk$PagedAsyncListCompletionHandler.onCompleted(Zendesk.java:2040)
```
--

**To Reproduce**
See error

**Expected behavior**
Not crash when trying to log. 

Would it be possible that the client truncate large responses and not try to log endless amounts of debug information. Or alternatively allow the user to specify whether or not they want this debug logging when the client is constructued.

**Desktop (please complete the following information):**
Client library v0.8.0

**Comment by aheritier** [comment]
I am using the library with a big instance and I am doing a lot of big queries without no issues.
I am using SLF4J, LOGBACK or LOG4J as logging impl. Maybe the problem comes from `au.com.helixta.util.log`.
In any case you can reduce the logs verbosity to not use the debug logs. It depends of the logging implementation but you should be able to set `org.zendesk.client.v2=INFO`

The JVM option `-XX:+UseStringDeduplication` could potentially help a bit.
