### ISSUE TITLE
Number of allowed incremental export API requests per minute exceeded

### ISSUE THREAD

**Issue by aheritier** [cloudbees-oss/zendesk-java-client#319]
**Describe the bug**
Using incremental export APIs is now frequently failing with such error:

```
org.zendesk.client.v2.ZendeskResponseRateLimitException: HTTP/429: Too Many Requests - {"error":"APIRateLimitExceeded","description":"Number of allowed incremental export API requests per minute exceeded"}
	at org.zendesk.client.v2.Zendesk.complete(Zendesk.java:2367) ~[zendesk-java-client-0.11.0.jar:?]
	at org.zendesk.client.v2.Zendesk.access$1400(Zendesk.java:98) ~[zendesk-java-client-0.11.0.jar:?]
	at org.zendesk.client.v2.Zendesk$PagedIterable$PagedIterator.hasNext(Zendesk.java:2624) ~[zendesk-java-client-0.11.0.jar:?]
	at java.util.Spliterators$IteratorSpliterator.trySplit(Spliterators.java:1784) ~[?:?]
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:289) ~[?:?]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) ~[?:?]
Caused by: org.zendesk.client.v2.ZendeskResponseRateLimitException: HTTP/429: Too Many Requests - {"error":"APIRateLimitExceeded","description":"Number of allowed incremental export API requests per minute exceeded"}
	at org.zendesk.client.v2.Zendesk$PagedAsyncListCompletionHandler.onCompleted(Zendesk.java:2184) ~[zendesk-java-client-0.11.0.jar:?]
	at org.zendesk.client.v2.Zendesk$PagedAsyncListCompletionHandler.onCompleted(Zendesk.java:2164) ~[zendesk-java-client-0.11.0.jar:?]
	at org.asynchttpclient.AsyncCompletionHandler.onCompleted(AsyncCompletionHandler.java:66) ~[async-http-client-2.10.4.jar:?]
	at org.asynchttpclient.netty.NettyResponseFuture.loadContent(NettyResponseFuture.java:222) ~[async-http-client-2.10.4.jar:?]
	at org.asynchttpclient.netty.NettyResponseFuture.done(NettyResponseFuture.java:257) ~[async-http-client-2.10.4.jar:?]
	at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.finishUpdate(AsyncHttpClientHandler.java:241) ~[async-http-client-2.10.4.jar:?]
	at org.asynchttpclient.netty.handler.HttpHandler.handleChunk(HttpHandler.java:114) ~[async-http-client-2.10.4.jar:?]
	at org.asynchttpclient.netty.handler.HttpHandler.handleRead(HttpHandler.java:143) ~[async-http-client-2.10.4.jar:?]
	at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:78) ~[async-http-client-2.10.4.jar:?]
```

**To Reproduce**

my code is something like:

```
StreamSupport.stream(zendesk.getTicketsIncrementally(ZENDESK_USAGE_START_DATE).spliterator(), true).forEach(ticket -> {....}));
```

**Expected behavior**

We are throwing a `ZendeskResponseRateLimitException` which is good and provides a retry_next time in seconds. But at the API consumer level it is almost impossible to know where we were and restart from here. I am not sure if the API shouldn't take care `ZendeskResponseRateLimitException` exceptions and retry by itself ???

From my POV this problem comes from this limit which wasn't here before:

> You can make up to 10 requests per minute to these endpoints.

https://developer.zendesk.com/rest_api/docs/support/incremental_export

**Comment by aheritier** [comment]
I found an acceptable solution by simplifying my code.
To be able to continue where we are when the exception occurs I am using the `iterator` with something like:

```
try {
                        processIterator(count, zendesk.getTicketsIncrementally(ZENDESK_USAGE_START_DATE).iterator());
                    } catch (InterruptedException e) {
                        LOGGER.error("The update of tickets was interrupted", e);
                        // Restore interrupted state...
                        Thread.currentThread().interrupt();
                    }

    private void processIterator(AtomicLong count, Iterator<Ticket> ticketsIterator) throws InterruptedException {
        try {
            while (ticketsIterator.hasNext()) {
                Ticket ticket = ticketsIterator.next();
                supportCaseService.createOrUpdateCaseFromZendesk(ticket);
                count.incrementAndGet();
            }
        } catch (
            ZendeskResponseRateLimitException zdrrle) {
            LOGGER.warn("Zendesk Rate Limit!! The update of tickets was paused. We will continue in {} seconds",
                zdrrle.getRetryAfter());
            Thread.sleep(zdrrle.getRetryAfter() * 1000);
            processIterator(count, ticketsIterator);
        }
    }
```

**Comment by aheritier** [comment]
I consider the implementation ok in the current state. We should probably document this pattern
