### ISSUE TITLE
Stuck lookupUserByEmail operation

### ISSUE THREAD

**Issue by uladzimirFilipchanka** [cloudbees-oss/zendesk-java-client#88]
Hello, 

We've noticed an issue with lookupUserByEmail operation. Iterable result sometimes stuck on hasNext operation. We have next code:

```
Iterable<User> users = getClient().lookupUserByEmail(email);
if (users != null) {
    for (Iterator<User> iterator = users.iterator(); iterator.hasNext(); ) {
        User user = iterator.next();
        id = user.getId();
        break;
    }
}
```

It doesn't look very optimized actually... Anyway, hasNext stucked infinite on future.get()
Here is thread dump

```
Thread 11342: (state = BLOCKED)
 - sun.misc.Unsafe.park(boolean, long) @bci=0 (Compiled frame; information may be imprecise)
 - java.util.concurrent.locks.LockSupport.park(java.lang.Object) @bci=14, line=186 (Compiled frame)
 - java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt() @bci=1, line=834 (Interpreted frame)
 - java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(int) @bci=72, line=994 (Compiled frame)
 - java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(int) @bci=24, line=1303 (Interpreted frame)
 - java.util.concurrent.CountDownLatch.await() @bci=5, line=236 (Interpreted frame)
 - com.ning.http.client.providers.netty.future.NettyResponseFuture.get() @bci=4, line=152 (Interpreted frame)
 - org.zendesk.client.v2.Zendesk.complete(com.ning.http.client.ListenableFuture) @bci=1, line=1584 (Interpreted frame)
 - org.zendesk.client.v2.Zendesk.access$1200(com.ning.http.client.ListenableFuture) @bci=1, line=74 (Interpreted frame)
 - org.zendesk.client.v2.Zendesk$PagedIterable$PagedIterator.hasNext() @bci=73, line=1761 (Interpreted frame)
```

We've found a thread stucked for 4 days. 
I don't know root issue for this, maybe Zendesk doesn't answer. 
Could you please advice?

**Comment by jon-ruckwood** [comment]
This may be related to https://github.com/AsyncHttpClient/async-http-client/issues/1070

I recently experienced something similar with a different API call. It seems, in my case, the request was in progress when a Zendesk outage occurred. Here's the thread dump I captured:

```
Foo-1 id=19 state=WAITING
    - waiting on <0x55f017db> (a java.util.concurrent.CountDownLatch$Sync)
    - locked <0x55f017db> (a java.util.concurrent.CountDownLatch$Sync)
    at sun.misc.Unsafe.park(Native Method)
    at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
    at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
    at com.ning.http.client.providers.netty.future.NettyResponseFuture.get(NettyResponseFuture.java:152)
    at org.zendesk.client.v2.Zendesk.complete(Zendesk.java:1637)
    at org.zendesk.client.v2.Zendesk.updateTicket(Zendesk.java:248)
```

**Comment by slandelle** [comment]
@stephenc I recommend you upgrade from AHC 1.9.15 to 1.9.31, and then to AHC 2.0.0 when it's finally released (in RC phase atm, ETA March).
